updating workflow

diff --git a/.github/workflows/main_swe40006-web-app.yml b/.github/workflows/main_swe40006-web-app.yml
--- a/.github/workflows/main_swe40006-web-app.yml
+++ b/.github/workflows/main_swe40006-web-app.yml
@@ -3,7 +3,7 @@ name: Feature Development Workflow
 on:
   push:
     branches:
-      - 'test'
+      - 'main'
 
 jobs:
   build_test:
@@ -29,7 +29,12 @@ jobs:
 
       - name: Run PHPUnit Tests
         id: phpunit
-        run: ./vendor/bin/phpunit
+        run: |
+          ./vendor/bin/phpunit
+          if [ $? -ne 0 ]; then
+            echo "PHPUnit tests failed."
+            exit 1  # This will fail the job
+          fi
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
@@ -47,15 +52,6 @@ jobs:
         with:
           name: php-app
 
-      - name: 'Deploy to Azure Web App - Test'
-        uses: azure/webapps-deploy@v2
-        id: deploy-to-test-webapp
-        with:
-          app-name: 'SWE40006-Web-App-Test'
-          slot-name: 'Production'
-          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST  }}
-          package: .
-
       - name: 'Deploy to Azure Web App - Production'
         id: deploy-to-webapp  
         if: ${{ needs.build_test.result == 'success' }}
@@ -65,16 +61,3 @@ jobs:
           slot-name: 'Production'
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
           package: .
-
-  merge-branch:
-    runs-on: ubuntu-latest
-    needs: build_test
-    steps:
-      - uses: actions/checkout@master
-
-      - name: Merge test -> main
-        uses: devmasx/merge-branch@master
-        with:
-          type: now
-          target_branch: main
-          github_token: ${{ secrets.GITHUB_TOKEN }}
